# Generated by Django 5.2.12 on 2026-03-04 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='christian',
            name='christian_roll_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='christian',
            name='church_id',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='christian',
            name='record_entry_year_eth',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
