# Generated by Django 5.2.12 on 2026-03-06 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_christian_christian_roll_number_christian_church_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='christian',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
