# Generated by Django 5.2.12 on 2026-03-10 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0002_alter_useraccount_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='requires_password_change',
            field=models.BooleanField(default=True),
        ),
    ]
