# Generated by Django 5.2.12 on 2026-03-06 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sundayschool',
            name='logo',
        ),
        migrations.AddField(
            model_name='sundayschool',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sundayschool',
            name='primary_color',
            field=models.CharField(default='#1e3a8a', help_text='Hex code for primary brand', max_length=7),
        ),
        migrations.AddField(
            model_name='sundayschool',
            name='primary_logo',
            field=models.ImageField(blank=True, help_text='Full logo for headers', null=True, upload_to='org/logos/'),
        ),
        migrations.AddField(
            model_name='sundayschool',
            name='secondary_color',
            field=models.CharField(default='#fbbf24', help_text='Hex code for secondary brand', max_length=7),
        ),
        migrations.AddField(
            model_name='sundayschool',
            name='symbol_logo',
            field=models.ImageField(blank=True, help_text='Small symbol for sidebar/favicon', null=True, upload_to='org/logos/'),
        ),
    ]
