# Generated by Django 5.2.12 on 2026-03-11 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0002_remove_sundayschool_logo_sundayschool_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sundayschool',
            name='primary_color',
            field=models.CharField(default='#162736', help_text='Hex code for primary brand', max_length=7),
        ),
        migrations.AlterField(
            model_name='sundayschool',
            name='secondary_color',
            field=models.CharField(default='#FCEB9E', help_text='Hex code for secondary brand', max_length=7),
        ),
    ]
