# Generated by Django 5.2.12 on 2026-03-04 19:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_day_of_week', models.IntegerField(blank=True, help_text='0=Monday, 6=Sunday', null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order_no', models.IntegerField()),
                ('is_custom', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_custom', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='StudentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_default', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('LATE', 'Late'), ('EXCUSED', 'Excused')], max_length=20)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_attendance_records', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceEditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edited_at', models.DateTimeField(auto_now_add=True)),
                ('reason_note', models.TextField()),
                ('before_status', models.CharField(max_length=20)),
                ('after_status', models.CharField(max_length=20)),
                ('edited_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_edits', to=settings.AUTH_USER_MODEL)),
                ('attendance_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_logs', to='sundayschool.attendancerecord')),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date_eth_year', models.IntegerField()),
                ('session_date_eth_month', models.IntegerField()),
                ('session_date_eth_day', models.IntegerField()),
                ('session_date_greg', models.DateField()),
                ('scope_type', models.CharField(choices=[('CLASSGROUP', 'Class Group'), ('WHOLE_SS', 'Whole Sunday School'), ('SPECIAL_EVENT', 'Special Event')], max_length=20)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('event_type', models.CharField(choices=[('REGULAR', 'Regular'), ('SPECIAL', 'Special')], default='REGULAR', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('state', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved')], default='DRAFT', max_length=20)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_attendance_sessions', to=settings.AUTH_USER_MODEL)),
                ('class_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sundayschool.classgroup')),
            ],
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='attendance_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='sundayschool.attendancesession'),
        ),
        migrations.CreateModel(
            name='AttendanceApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('comment', models.TextField()),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_attendances', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submitted_attendances', to=settings.AUTH_USER_MODEL)),
                ('attendance_session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='approval', to='sundayschool.attendancesession')),
            ],
        ),
        migrations.AddField(
            model_name='classgroup',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sundayschool.grade'),
        ),
        migrations.AddField(
            model_name='classgroup',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sundayschool.section'),
        ),
        migrations.CreateModel(
            name='SSStudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssid', models.CharField(max_length=20, unique=True)),
                ('joined_year_eth', models.IntegerField()),
                ('ss_roll_number', models.IntegerField()),
                ('registration_state', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_HR', 'Pending HR Approval'), ('PENDING_LEADER', 'Pending Leader Approval'), ('ACTIVE', 'Active'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=20)),
                ('profile_update_state', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('christian', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ss_profile', to='people.christian')),
                ('confession_father', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='people.confessionfather')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sundayschool.grade')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sundayschool.section')),
                ('student_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sundayschool.studentstatus')),
            ],
        ),
        migrations.CreateModel(
            name='GradeSectionChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('drafted_at', models.DateTimeField(auto_now_add=True)),
                ('hr_approved_at', models.DateTimeField(blank=True, null=True)),
                ('hr_comment', models.TextField(blank=True)),
                ('leader_approved_at', models.DateTimeField(blank=True, null=True)),
                ('leader_comment', models.TextField(blank=True)),
                ('state', models.CharField(default='DRAFT', max_length=20)),
                ('drafted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='drafted_gs_changes', to=settings.AUTH_USER_MODEL)),
                ('from_grade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_from', to='sundayschool.grade')),
                ('hr_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_approved_gs_changes', to=settings.AUTH_USER_MODEL)),
                ('leader_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leader_approved_gs_changes', to=settings.AUTH_USER_MODEL)),
                ('to_grade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_to', to='sundayschool.grade')),
                ('from_section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_from', to='sundayschool.section')),
                ('to_section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_to', to='sundayschool.section')),
                ('ss_student_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sundayschool.ssstudentprofile')),
            ],
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='ss_student_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sundayschool.ssstudentprofile'),
        ),
        migrations.CreateModel(
            name='StudentProfileUpdateRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changes_payload', models.JSONField()),
                ('drafted_at', models.DateTimeField(auto_now_add=True)),
                ('hr_approved_at', models.DateTimeField(blank=True, null=True)),
                ('hr_comment', models.TextField(blank=True)),
                ('state', models.CharField(choices=[('PENDING_HR', 'Pending HR'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING_HR', max_length=20)),
                ('drafted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='drafted_profile_updates', to=settings.AUTH_USER_MODEL)),
                ('hr_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_approved_profile_updates', to=settings.AUTH_USER_MODEL)),
                ('ss_student_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sundayschool.ssstudentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='StudentRegistrationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drafted_at', models.DateTimeField(auto_now_add=True)),
                ('hr_approved_at', models.DateTimeField(blank=True, null=True)),
                ('hr_comment', models.TextField(blank=True)),
                ('leader_approved_at', models.DateTimeField(blank=True, null=True)),
                ('leader_comment', models.TextField(blank=True)),
                ('state', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_HR', 'Pending HR Approval'), ('PENDING_LEADER', 'Pending Leader Approval'), ('ACTIVE', 'Active'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=20)),
                ('drafted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='drafted_registrations', to=settings.AUTH_USER_MODEL)),
                ('hr_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_approved_registrations', to=settings.AUTH_USER_MODEL)),
                ('leader_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leader_approved_registrations', to=settings.AUTH_USER_MODEL)),
                ('ss_student_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sundayschool.ssstudentprofile')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='classgroup',
            unique_together={('grade', 'section')},
        ),
        migrations.AlterUniqueTogether(
            name='attendancerecord',
            unique_together={('attendance_session', 'ss_student_profile')},
        ),
        migrations.CreateModel(
            name='StudentContactLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False)),
                ('contact_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.contactperson')),
                ('ss_student_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_links', to='sundayschool.ssstudentprofile')),
            ],
            options={
                'unique_together': {('ss_student_profile', 'contact_person')},
            },
        ),
    ]
