# Generated by Django 5.2.12 on 2026-03-06 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_christian_is_active'),
        ('sundayschool', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ssstudentprofile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='ssstudentprofile',
            name='christian',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='ss_profile', to='people.christian'),
        ),
        migrations.AlterField(
            model_name='ssstudentprofile',
            name='ss_roll_number',
            field=models.IntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='ssstudentprofile',
            name='ssid',
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
    ]
