# Generated by Django 5.2.12 on 2026-03-04 19:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_type', models.CharField(choices=[('ATTENDANCE', 'Attendance'), ('STUDENTS', 'Students')], max_length=50)),
                ('source', models.CharField(max_length=100)),
                ('file_name', models.CharField(max_length=255)),
                ('format', models.CharField(max_length=10)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('STARTED', 'Started'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('COMPLETED_WITH_ERRORS', 'Completed with Errors')], default='STARTED', max_length=50)),
                ('summary_counts', models.JSONField(default=dict, help_text="e.g., {'total': 100, 'success': 90, 'errors': 10}")),
                ('started_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='import_runs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ImportRowError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.IntegerField()),
                ('error_code', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('raw_payload', models.TextField(help_text='The raw row data that failed')),
                ('import_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='row_errors', to='imports.importrun')),
            ],
        ),
    ]
