# Generated by Django 5.2.12 on 2026-03-10 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.IntegerField()),
                ('error_code', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('raw_payload', models.TextField(help_text='The raw row data that failed')),
                ('import_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_logs', to='imports.importrun')),
            ],
        ),
    ]
