# Generated by Django 5.2.12 on 2026-03-04 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sundayschool', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MezemranMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mezmur_entry_year_eth', models.IntegerField()),
                ('mezemran_roll_number', models.IntegerField()),
                ('mezemran_id', models.CharField(max_length=30, unique=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('TERMINATED', 'Terminated')], default='ACTIVE', max_length=20)),
                ('selected_at', models.DateTimeField()),
                ('selection_reason', models.TextField()),
                ('criteria_used', models.TextField(blank=True)),
                ('terminated_at', models.DateTimeField(blank=True, null=True)),
                ('termination_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('selected_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='selected_mezemran', to=settings.AUTH_USER_MODEL)),
                ('ss_student_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mezemran_memberships', to='sundayschool.ssstudentprofile')),
                ('terminated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='terminated_mezemran', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MezemranChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('SELECT', 'Select'), ('TERMINATE', 'Terminate'), ('RESELECT', 'Reselect')], max_length=20)),
                ('payload', models.JSONField(help_text='Stores reasons, notes, criteria for the change')),
                ('drafted_at', models.DateTimeField(auto_now_add=True)),
                ('melody_exec_approved_at', models.DateTimeField(blank=True, null=True)),
                ('melody_exec_comment', models.TextField(blank=True)),
                ('leader_approved_at', models.DateTimeField(blank=True, null=True)),
                ('leader_comment', models.TextField(blank=True)),
                ('state', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_MELODY_EXEC', 'Pending Melody Exec'), ('PENDING_LEADER', 'Pending Leader'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=20)),
                ('drafted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='drafted_mz_changes', to=settings.AUTH_USER_MODEL)),
                ('leader_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leader_approved_mz', to=settings.AUTH_USER_MODEL)),
                ('melody_exec_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='melody_exec_approved_mz', to=settings.AUTH_USER_MODEL)),
                ('ss_student_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sundayschool.ssstudentprofile')),
                ('target_membership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='melody.mezemranmembership')),
            ],
        ),
    ]
