# Generated by Django 5.2.12 on 2026-03-06 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('melody', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mezemranmembership',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
